### ISSUE TITLE
'existing backups' prompts in --automatic mode

### ISSUE THREAD

**Issue by drewp** [felixrieseberg/slack-archive#21]
`npx slack-archive --automatic` is mostly automatic, but it can still stop on this prompt:

`? We've found existing backups (data_backup_1659373689529). Do you want to delete them?`

I think that should be an automatic yes (or no?).

**Comment by cheapsteak** [comment]
would be fixed by https://github.com/felixrieseberg/slack-archive/pull/15 once @felixrieseberg has a chance to take a look  🙏
