### ISSUE TITLE
Users and avatar aren't display anywhere

### ISSUE THREAD

**Issue by abeldotam** [felixrieseberg/slack-archive#6]
Hi, the current asked permission on the readme doesn't provide information about user nor their avatars.
We only have generic ID (at the best) or nothing, and no avatar.
![image](https://user-images.githubusercontent.com/5216201/159436864-35cf23ab-8d4f-4efd-ae94-1526fb2755ec.png)

The sender part, where it's supposed to be is empty.

![image](https://user-images.githubusercontent.com/5216201/159436949-20a4d177-3acb-49e9-bd27-b6cd79338091.png)

I also try with additionnal users scopes, [provided by this PR,](https://github.com/felixrieseberg/slack-archive/pull/5) but wasn't functionnal either.

Could you have an idea on how to fix it? 🙂

Thank you for your work, tho. Deeply appreciate it, seems the best slack archived I've met so far!

**Comment by ziyaointl** [comment]
While debugging this, I found that running the script manually again (so that it appends to the data already downloaded first time) makes the users and avatars show up. Not sure why though...

**Comment by abeldotam** [comment]
Thanks, indeed it worked! 🙏☺️
